/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookingair;

/**
 *
 * @author santi
 */
public class PanelVuelos extends javax.swing.JPanel {

    /**
     * Creates new form PanelVuelos
     */
    public PanelVuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableVuelos = new javax.swing.JScrollPane();
        TablaVuelos = new javax.swing.JTable();

        setBackground(new java.awt.Color(11, 9, 10));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 26, 29), 2, true));

        TablaVuelos.setAutoCreateRowSorter(true);
        TablaVuelos.setBackground(new java.awt.Color(245, 243, 244));
        TablaVuelos.setForeground(new java.awt.Color(255, 255, 255));
        TablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Trayecto", "Hora", "Precio"
            }
        ));
        TablaVuelos.setEnabled(false);
        TablaVuelos.setGridColor(new java.awt.Color(11, 9, 10));
        TableVuelos.setViewportView(TablaVuelos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TableVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TableVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVuelos;
    private javax.swing.JScrollPane TableVuelos;
    // End of variables declaration//GEN-END:variables
}
